{"ast":null,"code":"import { jsxDEV as _jsxDEV } from \"react/jsx-dev-runtime\";\nvar _jsxFileName = \"/home/alin/alinSpinjitzu/udemy courses/8_Complete React Developer in 2020/25_react_e-store/src/hoc/withErrorHandler/withErrorHandler.js\";\nimport { Component } from 'react';\nimport ErrorComponent from '../../components/UI/ErrorComponet/ErrorComponent';\n\nconst withErrorHandler = WrappedComponent => {\n  var _temp;\n\n  return _temp = class extends Component {\n    constructor(props) {\n      super(props);\n\n      this.errorShow = () => {\n        this.state.hasError && /*#__PURE__*/_jsxDEV(ErrorComponent, {\n          hasError: this.state.hasError\n        }, void 0, false, {\n          fileName: _jsxFileName,\n          lineNumber: 19,\n          columnNumber: 30\n        }, this);\n      };\n\n      this.state = {\n        hasError: false\n      };\n    }\n\n    static getDerivedStateFromError(error) {\n      return {\n        hasError: true\n      };\n    }\n\n    componentDidCatch(error, info) {}\n\n    render() {\n      return /*#__PURE__*/_jsxDEV(WrappedComponent, { ...this.props\n      }, void 0, false, {\n        fileName: _jsxFileName,\n        lineNumber: 23,\n        columnNumber: 14\n      }, this);\n    }\n\n  }, _temp;\n};\n\nexport default withErrorHandler; // class ErrorBoundary extends Component {\n//   constructor(props) {\n//     super(props);\n//     this.state = { hasError: false };\n//   }\n//   static getDerivedStateFromError(error) {\n//     return { hasError: true };\n//   }\n//   componentDidCatch(error, info) {}\n//   render() {\n//     if (this.state.hasError) {\n//       return <ErrorComponent hasError={this.state.hasError} />;\n//     }\n//     return this.props.children;\n//   }\n// }\n// export default ErrorBoundary;","map":{"version":3,"sources":["/home/alin/alinSpinjitzu/udemy courses/8_Complete React Developer in 2020/25_react_e-store/src/hoc/withErrorHandler/withErrorHandler.js"],"names":["Component","ErrorComponent","withErrorHandler","WrappedComponent","constructor","props","errorShow","state","hasError","getDerivedStateFromError","error","componentDidCatch","info","render"],"mappings":";;AAAA,SAASA,SAAT,QAA0B,OAA1B;AAEA,OAAOC,cAAP,MAA2B,kDAA3B;;AAEA,MAAMC,gBAAgB,GAAIC,gBAAD,IAAsB;AAAA;;AAC7C,iBAAO,cAAcH,SAAd,CAAwB;AAC7BI,IAAAA,WAAW,CAACC,KAAD,EAAQ;AACjB,YAAMA,KAAN;;AADiB,WAWnBC,SAXmB,GAWP,MAAM;AAChB,aAAKC,KAAL,CAAWC,QAAX,iBAAuB,QAAC,cAAD;AAAgB,UAAA,QAAQ,EAAE,KAAKD,KAAL,CAAWC;AAArC;AAAA;AAAA;AAAA;AAAA,gBAAvB;AACD,OAbkB;;AAEjB,WAAKD,KAAL,GAAa;AAAEC,QAAAA,QAAQ,EAAE;AAAZ,OAAb;AACD;;AAED,WAAOC,wBAAP,CAAgCC,KAAhC,EAAuC;AACrC,aAAO;AAAEF,QAAAA,QAAQ,EAAE;AAAZ,OAAP;AACD;;AAEDG,IAAAA,iBAAiB,CAACD,KAAD,EAAQE,IAAR,EAAc,CAAE;;AAMjCC,IAAAA,MAAM,GAAG;AACP,0BAAO,QAAC,gBAAD,OAAsB,KAAKR;AAA3B;AAAA;AAAA;AAAA;AAAA,cAAP;AACD;;AAlB4B,GAA/B;AAoBD,CArBD;;AAuBA,eAAeH,gBAAf,C,CAEA;AACA;AACA;AACA;AACA;AAEA;AACA;AACA;AAEA;AAEA;AACA;AACA;AACA;AAEA;AACA;AACA;AAEA","sourcesContent":["import { Component } from 'react';\n\nimport ErrorComponent from '../../components/UI/ErrorComponet/ErrorComponent';\n\nconst withErrorHandler = (WrappedComponent) => {\n  return class extends Component {\n    constructor(props) {\n      super(props);\n      this.state = { hasError: false };\n    }\n\n    static getDerivedStateFromError(error) {\n      return { hasError: true };\n    }\n\n    componentDidCatch(error, info) {}\n\n    errorShow = () => {\n      this.state.hasError && <ErrorComponent hasError={this.state.hasError} />;\n    };\n\n    render() {\n      return <WrappedComponent {...this.props} />;\n    }\n  };\n};\n\nexport default withErrorHandler;\n\n// class ErrorBoundary extends Component {\n//   constructor(props) {\n//     super(props);\n//     this.state = { hasError: false };\n//   }\n\n//   static getDerivedStateFromError(error) {\n//     return { hasError: true };\n//   }\n\n//   componentDidCatch(error, info) {}\n\n//   render() {\n//     if (this.state.hasError) {\n//       return <ErrorComponent hasError={this.state.hasError} />;\n//     }\n\n//     return this.props.children;\n//   }\n// }\n\n// export default ErrorBoundary;\n"]},"metadata":{},"sourceType":"module"}